import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY || 're_LcuLk8Qz_JgHWm5tnSXk6VcdkdSADBC22')

export async function POST(request: NextRequest) {
  try {
    const { name, email, phone, company, preferredDate, preferredTime, meetingType, agenda, source } = await request.json()
    
    console.log('Meeting request received:', { name, email, phone, company, preferredDate, preferredTime, meetingType, agenda, source })
    
    // Send email using Resend
    const emailResponse = await resend.emails.send({
      from: process.env.FROM_EMAIL || 'avaone@matchbestsoftware.ae',
      to: [process.env.FORM_QUERY_SUBMIT_EMAIL || 'pavan.satpute1@matchbest.ai'],
      subject: `🗓️ New Meeting Request from ${name} - ${company}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #6366f1; border-bottom: 2px solid #6366f1; padding-bottom: 10px;">
            📅 New Meeting Request
          </h2>
          
          <div style="background: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="color: #1e293b; margin-top: 0;">Contact Information</h3>
            <p><strong>Name:</strong> ${name}</p>
            <p><strong>Email:</strong> ${email}</p>
            <p><strong>Phone:</strong> ${phone}</p>
            <p><strong>Company:</strong> ${company}</p>
            <p><strong>Source:</strong> ${source}</p>
          </div>
          
          <div style="background: #fef3c7; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="color: #92400e; margin-top: 0;">Meeting Details</h3>
            <p><strong>Preferred Date:</strong> ${preferredDate}</p>
            <p><strong>Preferred Time:</strong> ${preferredTime}</p>
            <p><strong>Meeting Type:</strong> ${meetingType}</p>
            <p><strong>Agenda:</strong></p>
            <div style="background: white; padding: 15px; border-radius: 5px; border-left: 4px solid #f59e0b;">
              ${agenda}
            </div>
          </div>
          
          <div style="background: #dcfce7; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="color: #166534; margin-top: 0;">Next Steps</h3>
            <ul style="color: #166534;">
              <li>Review the meeting request details</li>
              <li>Check calendar availability for the preferred date/time</li>
              <li>Contact ${name} at ${email} or ${phone}</li>
              <li>Send calendar invitation with meeting details</li>
            </ul>
          </div>
          
          <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e2e8f0;">
            <p style="color: #64748b; font-size: 14px;">
              This meeting request was generated by AVA Voice Assistant<br>
              Timestamp: ${new Date().toLocaleString()}
            </p>
          </div>
        </div>
      `
    })
    
    console.log('✅ Meeting request email sent successfully:', emailResponse)
    
    return NextResponse.json({ 
      success: true, 
      message: 'Meeting request sent successfully',
      emailId: emailResponse.data?.id
    })
    
  } catch (error: any) {
    console.error('❌ Error sending meeting request:', error)
    return NextResponse.json(
      { error: 'Failed to send meeting request: ' + error.message },
      { status: 500 }
    )
  }
}
